# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         HTML-Seamstress
version:      2.9
version_from: lib/HTML/Seamstress.pm
installdirs:  site
requires:
    HTML::Tree:                    3.18
    Scalar::Listify:               0.02
    Tie::Cycle:                    1.06

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
