# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         HTML-Seamstress
version:      2.91
version_from: lib/HTML/Seamstress.pm
installdirs:  site
requires:
    AppConfig::Std:                1.07
    HTML::Tree:                    3.18
    Pod::Usage:                    1.16
    Scalar::Listify:               0.02
    Tie::Cycle:                    1.06

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
